#pragma once

#define ESP_COMMANDER_DEBUG

#ifndef ESP_COMMANDER_SCHEMA_QUERY
#define ESP_COMMANDER_SCHEMA_QUERY "__SCHEMA__"
#endif

#ifndef ESP_COMMANDER_JSON_BUFFER_SIZE
#define ESP_COMMANDER_JSON_BUFFER_SIZE 8192
#endif

#ifndef ESP_COMMANDER_MAX_PARAMETERS
#define ESP_COMMANDER_MAX_PARAMETERS 8
#endif

#ifndef ESP_COMMANDER_MAX_RESULTS
#define ESP_COMMANDER_MAX_RESULTS 8
#endif

#ifndef ESP_COMMANDER_MAX_QUERIES
#define ESP_COMMANDER_MAX_QUERIES 8
#endif

#ifndef ESP_COMMANDER_MAX_ACTIONS
#define ESP_COMMANDER_MAX_ACTIONS 8
#endif

#ifndef ESP_COMMANDER_MAX_ENUM_SIZE
#define ESP_COMMANDER_MAX_ENUM_SIZE 8
#endif